version: '3.8'

services:
  garage:
    build: .
    container_name: garage
    restart: unless-stopped
    network_mode: host
    privileged: true
    devices:
      - /dev/gpiomem:/dev/gpiomem
    labels:
      - "traefik.enable=false"
